version: "3.2"
services:
  auth-app:
    build:
      context: ./auth-app
    volumes:
    - ./auth-app:/var/www/auth-app
    working_dir: /var/www/auth-app
  auth-nginx:
    build:
      context: ./auth-nginx
    volumes:
    - ./auth-app/public:/var/www/auth-app/public
  auth-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
  films-app:
    build:
      context: ./films-app
    volumes:
    - ./films-app:/var/www/films-app
    working_dir: /var/www/films-app
  films-nginx:
    build:
      context: ./films-nginx
    volumes:
    - ./films-app/public:/var/www/films-app/public
  films-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/var/www/swagger
    environment:
      SWAGGER_JSON: /var/www/swagger/swagger.json
